version: '3.8'
services:
  web:
    image: node:14
    working_dir: /app
    volumes:
      - ./public:/app/public
      - ./app.js:/app/app.js
    command: node app.js
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
